### PR TITLE
Add support for Python 3.7 (PEP479: StopIteration has been deprecated for generators)

### PR DESCRIPTION
**Pull request by wosc**

### CODE REVIEW

**Comment by jugmac00** [comment]
Please update the Travis config, also.

Is there a reason you do not include Python 3.8?

**Comment by wosc** [comment]
Ah. No, I simply forgot. I've updated the commit now.

**Comment by wosc** [comment]
What kind of changelog note should I write, other than [Add support for Python 3.7 and 3.8](https://github.com/zopefoundation/zope.file/pull/7/files#diff-db23dcd814354c954091a9b90dbfd92aR8)?

**Comment by icemac** [comment]
Any news on this PR?

**Comment by jamadden** [comment]
LGTM! The change log looks fine now. @wosc is a member and could merge the PR, but so could any other member, I think.

**Comment by mgedmin** [comment]
My preferred workflow is that the person who created the PR gets to hit the Merge button after getting an approval (or after a reasonable timeout if nobody volunteers to review, e.g. a week).  I have reasons for this:

- it's pleasant to hit the Merge button and the contributor deserves that
- sometimes code review leaves optional suggestions and the original contributor can choose if they want to implement them or not
- this way we can be sure any required contributor agreements have been signed and won't accidentally merge code we're not supposed to merge

**Comment by wosc** [comment]
Ah! I didn't understand the workflow (I'm more used to the rule "the reviewer merges, not the committer"), but you're quite right, it's kind of satisfying. :)

**Comment by wosc** [comment]
I don't have pypi rights for this package though, so it would be great if someone else could cut a release.

**Comment by mgedmin** [comment]
No worries -- we've been really bad about communicating the expected workflow and everything!

(Also, it's more of a thing I just decided personally and not official ZF policy ;)

**Comment by mgedmin** [comment]
I released zope.file 1.2.0.

**Pull request merged**
